spring:
  application:
    name: config-sever
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
  profiles:
    active: native
server:
  port: 8888

